name: zizmor-bp
base: core24
adopt-info: zizmor
summary: Static analysis for GitHub Actions
description: |
  zizmor is a static analysis tool for GitHub Actions. It can find and fix many
  common security issues in typical GitHub Actions CI/CD setups.
grade: stable
confinement: strict

apps:
  zizmor:
    command: zizmor
    plugs: [home, network]

parts:
  zizmor:
    plugin: rust
    rust-channel: stable
    source: .
    build-packages:
    - git
    override-build: |
      # build the latest tagged release
      latest_tag=$(git tag --list | grep '^v' | sort -V | tail -1)
      git checkout ${latest_tag?}
      craftctl set version=$(git describe --tags)
      craftctl default
    override-prime: |
      find .
      craftctl default
